### ISSUE TITLE
Output variable for the pull request made

### ISSUE THREAD

**Issue by CaseyPeters** [TreTuna/sync-branches#24]
Not sure how difficult this would be, but it would be awesome if we could somehow output the PR number so that I could pass it to another step to send a slack message.

**Comment by CaseyPeters** [comment]
I tried to create a branch and push it up for review but I do not have permissions. This should be the change needed in order to access that variable in another step.

![image](https://user-images.githubusercontent.com/27693216/75192930-7ad48f80-5712-11ea-917d-21e668356ad4.png)

**Comment by TreTuna** [comment]
I like this idea. I'll run through and add this tonight with a little addition. If there is already a PR open, meaning that these commits would then be added to that PR, we should set this output variable to that URL in the `else` statement.

**Comment by TreTuna** [comment]
Just released v1.1.0 with this functionality added.

PR:
https://github.com/TreTuna/sync-branches/pull/25

Release:
https://github.com/marketplace/actions/sync-branches
