### ISSUE TITLE
Feature to sync multiple branches with one FROM/source branch

### ISSUE THREAD

**Issue by sudoStatus200** [TreTuna/sync-branches#35]
Hi, 

Thanks for this action. 
But I want to sync multiple branches with master. 
So I would like to add this feature of syncing multiple branches.
I am planning to take multiple branches from the user in comma separated form.
like this:
`TO_BRANCHS: "develop,staging,experiment-branch"`

and then make subsequent changes inside index.js
```
const toBranchs = core.getInput("TO_BRANCHS", { required: true });
const branchs = toBranchs.split(",");
//Then run a loop over array to create PR for each branch
//Might add limit to number of branches
```

Please, respond with your suggestions.

Thanks,

**Comment by sudoStatus200** [comment]
@TreTuna  Have created a new action from your codebase that meets my requirement.
I have mentioned your action in the readme as well.

**Comment by TreTuna** [comment]
Hey, sorry I missed this, I've been on vacation from code for the past two weeks. Definitely sounds like a good feature! Perhaps will add in here as well still.
